config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  root 'access#login'
  get 'login', to: "access#login", as: 'login'

  get 'signup', to: "access#signup", as: 'signup'

  post 'login', to: "access#attempt_login"

  post 'signup', to: "access#create"

  get 'home', to: "access#home", as: 'home'

  get 'logout', to: "access#logout"

  resources :password_resets
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username,
    presence: true,
    uniqueness: true
  validates_confirmation_of :password
	#attr_accessible :attribute1, attribute2
def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  UserMailer.password_reset(self).deliver
end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in, only: [:home]
  before_action :prevent_login_signup, only: [:signup, :login]

  def signup
    @user = User.new
  end

   def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You are now logged in!"
      redirect_to home_path
    else
      render :signup
    end
   end

  def login
  end

  def attempt_login

    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if !found_user
      flash.now[:alert] = "Invalid username"
      render :login

    elsif !authorized_user
      flash.now[:alert] = "Invalid password"
      render :login

    else
      session[:user_id] = authorized_user.id
      flash[:success] = "You are now logged in."
      redirect_to home_path
    end

  end

  def home

  end


  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to login_path
  end


  private
  def user_params
    params.require(:user).permit(:username, :password, :password_digest)
  end

  def confirm_logged_in
    unless session[:user_id]
      redirect_to login_path, alert: "Please log in"
    end
  end


  def prevent_login_signup
    if session[:user_id]
      redirect_to home_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

def create
  user = User.find_by_email(params[:email])
  user.send_password_reset if user
  redirect_to root_url, :notice => "Email sent with ↵
    password reset instructions."
end
def edit
  @user = User.find_by_password_reset_token!(params[:id])
end
def update
  @user = User.find_by_password_reset_token!(params[:id])
  if @user.password_reset_sent_at < 2.hours.ago
    redirect_to new_password_reset_path, :alert => "Password ↵
      reset has expired."
  elsif @user.update_attributes(params[:user])
    redirect_to root_url, :notice => "Password has been reset."
  else
    render :edit
  end
end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/access/forgotpassword.html.erb
<h1> Forgot Your Password?</h1>

<%= form_tag("/resetpassword", method: "get") do %>
  <%= label_tag(:q, "Email Address") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/access/home.html.erb
<h1>Welcome to our Website!</h1>

<%= link_to "Logout", logout_path, class:"btn btn-danger" %>

app/views/access/login.html.erb
<h1>Login</h1>

  <%= form_tag(login_path) do %>
<p>
  <%= label_tag(:username)%>
  <%= text_field_tag(:username, params[:username], autofocus: true)%>
</p>
<p>
  <%= label_tag(:password)%>
  <%= password_field_tag(:password)%>
</p>
<p>
  <%= submit_tag("Log in", class: "btn btn-primary") %>
</p>
<% end %>

<%= link_to "Don't have an account? Sign up here", signup_path%>

<%= link_to "Forgot your password? Click here", password_resets_path%>

app/views/access/resetpassword.html.erb
<h1> Reset Your Password </h1>

<%= form_for("/resetpassword", method: "post") do |f|%>
  <%= f.label("new password") %>
  <%= f.password_field :password %>
  <%= f.label("new password") %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit("Submit") %>
<% end %>

app/views/access/signup.html.erb
<h1>Signup</h1>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |error| %>
    <p class = "text-danger"><%= error %></p>
  <% end %>
<% end %>

<%= form_for(@user, url: signup_path) do |f|%>

<p>
  <%= f.label(:username) %>
  <%= f.text_field(:username, autofocus: true) %>
</p>
<p>
  <%= f.label(:password) %>
  <%= f.password_field(:password) %>
</p>
<p>
  <%= f.submit("Signup", class: "btn btn-primary") %>
</p>
  <%= link_to "Have an account already? Log in here", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body class = "container text-center">

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) ↵
  do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>